name: cargo test --workspace
on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build: [--release, ~]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Rust version
        run: |
          rustup --version
          rustc --version
          cargo --version

      - name: Run `cargo test --workspace`
        run: cargo test --workspace ${{ matrix.build }}
